### ISSUE TITLE
Tests fail: Wanted but not invoked: geoJsonSource.setGeoJson

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-plugins-android#17]
After merging #12, the tests fail: https://github.com/maplibre/maplibre-plugins-android/actions/runs/4255578822/jobs/7403370903

```
com.mapbox.mapboxsdk.plugins.annotation.FillManagerTest > testInitialization FAILED
    Wanted but not invoked:
    geoJsonSource.setGeoJson(
        <any com.mapbox.geojson.FeatureCollection>
    );
    -> at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(GeoJsonSource.java:291)
    Actually, there were zero interactions with this mock.
        at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(GeoJsonSource.java:291)
        at com.mapbox.mapboxsdk.plugins.annotation.FillManagerTest.testInitialization(FillManagerTest.java:68)
```

We should set up CI for pull requests so that we avoid this in the future.

**Comment by JonasVautherin** [comment]
Was solved in https://github.com/maplibre/maplibre-plugins-android/pull/35 by removing the tests. Would be nice to actually fix them, but that's more involved following #12.
